version: '3.3'

services:
  bot:
    build:
      context: .
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
      - PASSWORD=${DB_PASSWORD}
      - DB=${DB_NAME}
      - USER=${DB_USER}
    restart: on-failure
    depends_on:
      - db
      - redis

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis
    env_file:
      - .env
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./conf:/usr/local/etc/redis
      - ./redis_data:/data
    ports:
      - 6379:6379
    restart: always